# Definitive Mojibake fix using direct string replacement.
# 
# The files have been triple-encoded (UTF-8 -> read as Latin-1 -> saved as UTF-8, 3 times).
# The corruption patterns observed in the hex are sequences like:
#   C3 83 C6 92 C3 82 A1  which is "ÃƒÂ¡" and should be "á"  (U+00E1)
#
# Rather than byte manipulation, we use exact string replacement on the UTF-8 decoded content.
# The file IS valid UTF-8 on disk — it just has wrong text content.

$rootDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$frontDir = Join-Path $rootDir "front"

$utf8nob = New-Object System.Text.UTF8Encoding($false)

# Map of corrupted string -> correct string
# Generated by encoding each Portuguese char UTF-8, re-reading as Latin-1 twice.
# Pattern: each original UTF-8 2-byte char (C3 XX) becomes a 6+ char mojibake string.
$replacements = [ordered]@{
    # Compounds first (longer sequences before their substrings)
    "ÃƒÂ§ÃƒÂ£o"  = "ção"
    "ÃƒÂ§ÃƒÂµes" = "ções"
    "ÃƒÂ§ÃƒÂ£"   = "çã"
    "ÃƒÅ¡ltimas" = "Últimas"    # Ú special case (C3 9A -> Å¡ via triple encode)
    "ÃƒÅ¡"       = "Ú"
    "ÃƒÆ'"       = "Ã"          # intermediate artifact from triple encode of Ã
    # Individual characters
    "ÃƒÂµ"       = "õ"
    "ÃƒÂ§"       = "ç"
    "ÃƒÂ£"       = "ã"
    "ÃƒÂª"       = "ê"
    "ÃƒÂ©"       = "é"
    "ÃƒÂ³"       = "ó"
    "ÃƒÂ¡"       = "á"
    "ÃƒÂ­"       = "í"
    "ÃƒÂº"       = "ú"
    "Ãƒâ€œ"      = "Ó"
    "ÃƒÂ "       = "À"
    "Ãƒ "        = "Á"          # Á (U+00C1)
    "Ãƒâ€"       = "Â"
    "ÃƒÂ"        = "Â"          # fallback
}

$files = Get-ChildItem -Path $frontDir -Recurse -Filter "*.html" |
         Select-Object -ExpandProperty FullName

$fixedCount = 0

foreach ($file in $files) {
    # Read the file as UTF-8 text (it IS valid UTF-8, just garbled text)
    $content  = [System.IO.File]::ReadAllText($file, [System.Text.Encoding]::UTF8)
    $original = $content

    # Strip any leading UTF-8 BOM character if present as text
    $content = $content.TrimStart([char]0xFEFF)

    foreach ($pair in $replacements.GetEnumerator()) {
        $content = $content.Replace($pair.Key, $pair.Value)
    }

    if ($content -ne $original) {
        [System.IO.File]::WriteAllText($file, $content, $utf8nob)
        Write-Host "FIXED: $($file.Replace($frontDir + '\', ''))"
        $fixedCount++
    } else {
        Write-Host "OK:    $($file.Replace($frontDir + '\', ''))"
    }
}

Write-Host ""
Write-Host "Done. $fixedCount file(s) corrected."
